services:
  nextjs-app:    
    container_name: nextjs-app
    restart: always
    build:
      context: .
      args:
        - RESEND_API_KEY=${{ secrets.DATABASE_URL }}
    env_file:
      - .env
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app/public
 


   

