services:
  nextjs-app:    
    container_name: nextjs-app
    restart: always
    build:
      context: .
      args:
        - RESEND_API_KEY=${AUTH_SECRET}
        - API_URL=${API_URL}
        - AUTH_SECRET=${AUTH_SECRET}
    environment:
      - NODE_ENV: production
      - AUTH_SECRET: ${AUTH_SECRET}
      - API_URL: ${API_URL}
      - RESEND_API_KEY: ${RESEND_API_KEY}
    env_file:
      - .env
      - .env.local
    ports:
      - "3000:3000"
    
