services:
  nextjs-app:    
    container_name: nextjs-app
    restart: always
    build:
      context: .
      args:
        - RESEND_API_KEY=re_Rq6bLA4K_FxnGakKoT5WLJnS889Wpdo5J
    env_file:
      - .env
      - .env.local
    working_dir: /app/public
    volumes:
      - /c/Docker
    ports:
      - "3000:3000"

    


   

