services:
  nextjs-app:    
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nextjs.rule=Host(`go.heryheryanto.my.id`)"
        - "traefik.http.routers.nextjs.entrypoints=websecure"
        - "traefik.http.routers.nextjs.tls.certresolver=myresolver"
        - "traefik.http.middlewares.nextjs-headers.headers.customRequestHeaders.Cookie=true"
    container_name: nextjs-app
    restart: always
    build:
      context: .
      args:
        - RESEND_API_KEY=re_Rq6bLA4K_FxnGakKoT5WLJnS889Wpdo5J
        - API_URL=https://go.heryheryanto.my.id
    env_file:
      - .env
      - .env.local
    ports:
      - "3000:3000"
    
