services:
  nextjs-app:
    
    container_name: nextjs-app
    build:
      context: .
      args:
        - RESEND_API_KEY=re_Rq6bLA4K_FxnGakKoT5WLJnS889Wpdo5J
    env_file:
      - .env
      - .env.local
    ports:
      - "3000:3000"
    restart: always
<<<<<<< HEAD
    env_file:
      - .env-local
=======


   

>>>>>>> 08b989b08c08ee2d6e7605f09f99cb1abd89a98f
