services:
  nextjs-app:    
    container_name: nextjs-app
    restart: always
    build:
      context: .
      args:
        - RESEND_API_KEY: ${RESEND_API_KEY}
        - API_URL: ${API_URL}
    env_file:
      - .env
      - .env.local
    ports:
      - "3000:3000"
    
