services:
  nextjs-app:
    restart: always
    container_name: nextjs-app
    build:
      context: .
      args:
        - RESEND_API_KEY=${RESEND_API_KEY}
    env_file:
      - .env
      - .env.local
    ports:
      - "3000:3000"

    volumes:
      - nextjs:/app/public  # Ini adalah mount, bukan definisi volume

volumes:
  nextjs: # Ini adalah definisi named volume di level atas


   
