-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NULL,

    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Header` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `nomor_aju` VARCHAR(191) NOT NULL,
    `kode_dokumen` VARCHAR(191) NOT NULL,
    `kode_kantor` VARCHAR(191) NOT NULL,
    `kode_kantor_bongkar` VARCHAR(191) NOT NULL,
    `kode_kantor_periksa` VARCHAR(191) NOT NULL,
    `kode_kantor_tujuan` VARCHAR(191) NOT NULL,
    `kode_kantor_ekspor` VARCHAR(191) NOT NULL,
    `kode_jenis_impor` VARCHAR(191) NOT NULL,
    `kode_jenis_ekspor` VARCHAR(191) NOT NULL,
    `kode_jenis_tpb` VARCHAR(191) NOT NULL,
    `kode_jenis_plb` VARCHAR(191) NOT NULL,
    `kode_jenis_prosedur` VARCHAR(191) NOT NULL,
    `kode_tujuan_pemasukan` VARCHAR(191) NOT NULL,
    `kode_tujuan_pengiriman` VARCHAR(191) NOT NULL,
    `kode_tujuan_tpb` VARCHAR(191) NOT NULL,
    `kode_cara_dagang` VARCHAR(191) NOT NULL,
    `kode_cara_bayar` VARCHAR(191) NOT NULL,
    `kode_cara_bayar_lainnya` VARCHAR(191) NOT NULL,
    `kode_gudang_asal` VARCHAR(191) NOT NULL,
    `kode_gudang_tujuan` VARCHAR(191) NOT NULL,
    `kode_jenis_kirim` VARCHAR(191) NOT NULL,
    `kode_jenis_pengiriman` VARCHAR(191) NOT NULL,
    `kode_kategori_ekspor` VARCHAR(191) NOT NULL,
    `kode_kategori_masuk_ftz` VARCHAR(191) NOT NULL,
    `kode_kategori_keluar_ftz` VARCHAR(191) NOT NULL,
    `kode_kategori_barang_ftz` VARCHAR(191) NOT NULL,
    `kode_lokasi` VARCHAR(191) NOT NULL,
    `kode_lokasi_bayar` VARCHAR(191) NOT NULL,
    `lokasi_asal` VARCHAR(191) NOT NULL,
    `lokasi_tujuan` VARCHAR(191) NOT NULL,
    `kode_daerah_asal` VARCHAR(191) NOT NULL,
    `kode_negara_tujuan` VARCHAR(191) NOT NULL,
    `kode_tutup_pu` VARCHAR(191) NOT NULL,
    `nomor_bc11` VARCHAR(191) NOT NULL,
    `tanggal_bc11` VARCHAR(191) NOT NULL,
    `nomor_pos` VARCHAR(191) NOT NULL,
    `nomor_sub_pos` VARCHAR(191) NOT NULL,
    `kode_pelabuhan_bongkar` VARCHAR(191) NOT NULL,
    `kode_pelabuhan_muat` VARCHAR(191) NOT NULL,
    `kode_pelabuhan_muat_akhir` VARCHAR(191) NOT NULL,
    `kode_pelabuhan_transit` VARCHAR(191) NOT NULL,
    `kode_pelabuhan_tujuan` VARCHAR(191) NOT NULL,
    `kode_pelabuhan_ekspor` VARCHAR(191) NOT NULL,
    `kode_tps` VARCHAR(191) NOT NULL,
    `tanggal_berangkat` VARCHAR(191) NOT NULL,
    `tanggal_ekspor` VARCHAR(191) NOT NULL,
    `tanggal_masuk` VARCHAR(191) NOT NULL,
    `tanggal_muat` VARCHAR(191) NOT NULL,
    `tanggal_tiba` VARCHAR(191) NOT NULL,
    `tanggal_periksa` VARCHAR(191) NOT NULL,
    `tempat_stuffing` VARCHAR(191) NOT NULL,
    `tanggal_stuffing` VARCHAR(191) NOT NULL,
    `kode_tanda_pengaman` VARCHAR(191) NOT NULL,
    `jumlah_tanda_pengaman` VARCHAR(191) NOT NULL,
    `flag_curah` VARCHAR(191) NOT NULL,
    `flag_sda` VARCHAR(191) NOT NULL,
    `flag_vd` VARCHAR(191) NOT NULL,
    `flag_ap_bk` VARCHAR(191) NOT NULL,
    `flag_migas` VARCHAR(191) NOT NULL,
    `kode_asuransi` VARCHAR(191) NOT NULL,
    `asuransi` DECIMAL(65, 30) NOT NULL,
    `nilai_barang` DECIMAL(65, 30) NOT NULL,
    `nilai_incoterm` DECIMAL(65, 30) NOT NULL,
    `nilai_maklon` DECIMAL(65, 30) NOT NULL,
    `freight` DECIMAL(65, 30) NOT NULL,
    `fob` DECIMAL(65, 30) NOT NULL,
    `biaya_tambahan` DECIMAL(65, 30) NOT NULL,
    `biaya_pengurang` DECIMAL(65, 30) NOT NULL,
    `vd` DECIMAL(65, 30) NOT NULL,
    `cif` DECIMAL(65, 30) NOT NULL,
    `harga_penyerahan` DECIMAL(65, 30) NOT NULL,
    `ndpbm` DECIMAL(65, 30) NOT NULL,
    `total_dana_sawit` DECIMAL(65, 30) NOT NULL,
    `dasar_pengenaan_pajak` DECIMAL(65, 30) NOT NULL,
    `nilai_jasa` DECIMAL(65, 30) NOT NULL,
    `uang_muka` INTEGER NOT NULL,
    `bruto` INTEGER NOT NULL,
    `netto` INTEGER NOT NULL,
    `volume` INTEGER NOT NULL,
    `kota_pernyataan` VARCHAR(191) NOT NULL,
    `tanggal_pernyataan` VARCHAR(191) NOT NULL,
    `nama_pernyataan` VARCHAR(191) NOT NULL,
    `jabatan_pernyataan` VARCHAR(191) NOT NULL,
    `kode_valuta` VARCHAR(191) NOT NULL,
    `kode_incoterm` VARCHAR(191) NOT NULL,
    `kode_jasa_kena_pajak` VARCHAR(191) NOT NULL,
    `nomor_bukti_bayar` VARCHAR(191) NOT NULL,
    `tanggal_bukti_bayar` VARCHAR(191) NOT NULL,
    `kode_jenis_nilai` VARCHAR(191) NOT NULL,
    `nomor_daftar` VARCHAR(191) NOT NULL,
    `tanggal_daftar` DATETIME(3) NOT NULL,
    `create_by` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
