import { version } from "os";

const TransformData = (input: any) => {
    console.log("Data to export:", input);
    const header = [{
        'ASURANSI': input.asuransi,
        'BARANG KIRIMAN': input.barang_kiriman,
        'BARANG TIDAK BERWUJUD': input.barang_tidak_berwujud,
        'BIAYA PENGURANG': input.biaya_pengurang,
        'BIAYA TAMBAHAN': input.biaya_tambahan,
        'BRUTO': input.bruto,
        'CIF': input.cif,
        'DASAR PENGENAAN PAJAK': input.dasar_pengenaan_pajak,
        'FLAG AP BK': input.flag_ap_bk,
        'FLAG CURAH': input.flag_curah,
        'FLAG KONSOL': input.flag_konsol,
        'FLAG MIGAS': input.flag_migas,
        'FLAG PROPORSIONAL NETTO': input.flag_proporsional_netto,
        'FLAG SDA': input.flag_sda,
        'FLAG VD': input.flag_vd,
        'FOB': input.fob,
        'FREIGHT': input.freight,
        'HARGA PENYERAHAN': input.harga_penyerahan,
        'JABATAN PERNYATAAN': input.jabatan_pernyataan,
        'JAMINAN': input.jaminan,
        'JUMLAH TANDA PENGAMAN': input.jumlah_tanda_pengaman,
        'KEMASAN': input.kemasan,
        'KODE ASAL BARANG FTZ': input.kode_asal_barang_ftz,
        'KODE ASURANSI': input.kode_asuransi,
        'KODE CARA BAYAR': input.kode_cara_bayar,
        'KODE CARA BAYAR LAINNYA': input.kode_cara_bayar_lainnya,
        'KODE CARA DAGANG': input.kode_cara_dagang,
        'KODE DAERAH ASAL': input.kode_daerah_asal,
        'KODE DOKUMEN': input.kode_dokumen,
        'KODE GUDANG ASAL': input.kode_gudang_asal,
        'KODE GUDANG TUJUAN': input.kode_gudang_tujuan,
        'KODE INCOTERM': input.kode_incoterm,
        'KODE JASA KENA PAJAK': input.kode_jasa_kena_pajak,
        'KODE JENIS EKSPOR': input.kode_jenis_ekspor,
        'KODE JENIS IMPOR': input.kode_jenis_impor,
        'KODE JENIS KIRIM': input.kode_jenis_kirim,
        'KODE JENIS NILAI': input.kode_jenis_nilai,
        'KODE JENIS PENGANGKUTAN': input.kode_jenis_pengangkutan,
        'KODE JENIS PENGELUARAN': input.kode_jenis_pengeluaran,
        'KODE JENIS PENGIRIMAN': input.kode_jenis_pengiriman,
        'KODE JENIS PLB': input.kode_jenis_plb,
        'KODE JENIS PROSEDUR': input.kode_jenis_prosedur,
        'KODE JENIS TPB': input.kode_jenis_tpb,
        'KODE KANTOR': input.kode_kantor,
        'KODE KANTOR BONGKAR': input.kode_kantor_bongkar,
        'KODE KANTOR EKSPOR': input.kode_kantor_ekspor,
        'KODE KANTOR MUAT': input.kode_kantor_muat,
        'KODE KANTOR PERIKSA': input.kode_kantor_periksa,
        'KODE KANTOR TUJUAN': input.kode_kantor_tujuan,
        'KODE KATEGORI BARANG FTZ': input.kode_kategori_barang_ftz,
        'KODE KATEGORI EKSPOR': input.kode_kategori_ekspor,
        'KODE KATEGORI KELUAR FTZ': input.kode_kategori_keluar_ftz,
        'KODE KATEGORI MASUK FTZ': input.kode_kategori_masuk_ftz,
        'KODE LOKASI': input.kode_lokasi,
        'KODE LOKASI BAYAR': input.kode_lokasi_bayar,
        'KODE NEGARA TUJUAN': input.kode_negara_tujuan,
        'KODE PELABUHAN BONGKAR': input.kode_pelabuhan_bongkar,
        'KODE PELABUHAN EKSPOR': input.kode_pelabuhan_ekspor,
        'KODE PELABUHAN MUAT': input.kode_pelabuhan_muat,
        'KODE PELABUHAN MUAT AKHIR': input.kode_pelabuhan_muat_akhir,
        'KODE PELABUHAN TRANSIT': input.kode_pelabuhan_transit,
        'KODE PELABUHAN TUJUAN': input.kode_pelabuhan_tujuan,
        'KODE TANDA PENGAMAN': input.kode_tanda_pengaman,
        'KODE TPS': input.kode_tps,
        'KODE TUJUAN PEMASUKAN': input.kode_tujuan_pemasukan,
        'KODE TUJUAN PENGELUARAN': input.kode_tujuan_pengeluaran,
        'KODE TUJUAN PENGIRIMAN': input.kode_tujuan_pengiriman,
        'KODE TUJUAN TPB': input.kode_tujuan_tpb,
        'KODE TUTUP PU': input.kode_tutup_pu,
        'KODE VALUTA': input.kode_valuta,
        'KONTAINER': input.kontainer,
        'KOTA PERNYATAAN': input.kota_pernyataan,
        'LOKASI ASAL': input.lokasi_asal,
        'LOKASI TUJUAN': input.lokasi_tujuan,
        'NAMA PERNYATAAN': input.nama_pernyataan,
        'NDPBM': input.ndpbm,
        'NETTO': input.netto,
        'NILAI BARANG': input.nilai_barang,
        'NILAI INCOTERM': input.nilai_incoterm,
        'NILAI JASA': input.nilai_jasa,
        'NILAI MAKLON': input.nilai_maklon,
        'NOMOR AJU': input.nomor_aju,
        'NOMOR BC11': input.nomor_bc11,
        'NOMOR BUKTI BAYAR': input.nomor_bukti_bayar,
        'NOMOR DAFTAR': input.nomor_daftar,
        'NOMOR POS': input.nomor_pos,
        'NOMOR SUB POS': input.nomor_sub_pos,
        'PPN PAJAK': input.ppn_pajak,
        'PPNBM PAJAK': input.ppnbm_pajak,
        'TANGGAL BC11': input.tanggal_bc11,
        'TANGGAL BERANGKAT': input.tanggal_berangkat,
        'TANGGAL BUKTI BAYAR': input.tanggal_bukti_bayar,
        'TANGGAL DAFTAR': input.tanggal_daftar,
        'TANGGAL EKSPOR': input.tanggal_ekspor,
        'TANGGAL MASUK': input.tanggal_masuk,
        'TANGGAL MUAT': input.tanggal_muat,
        'TANGGAL PERIKSA': input.tanggal_periksa,
        'TANGGAL PERNYATAAN': input.tanggal_pernyataan,
        'TANGGAL STUFFING': input.tanggal_stuffing,
        'TANGGAL TIBA': input.tanggal_tiba,
        'TARIF PPN PAJAK': input.tarif_ppn_pajak,
        'TARIF PPNBM PAJAK': input.tarif_ppnbm_pajak,
        'TEMPAT STUFFING': input.tempat_stuffing,
        'TOTAL DANA SAWIT': input.total_dana_sawit,
        'UANG MUKA': input.uang_muka,
        'VD': input.vd,
        'VOLUME': input.volume,

    }]

    return {
        HEADER: header,
        ENTITAS: input.entitas ?? [],
        DOKUMEN: input.dokumen ?? [], // kalau ada array dokumen
        PENGANGKUT: input.pengangkut,
        KEMASAN: input.kemasan ?? [],
        KONTAINER: input.kontainer ?? [],
        KOMPONENBIAYA: input.komponen_biaya ?? [],
        BARANG: input.barang ?? [],   // kalau ada array barang
        BARANGTARIF: input.barang_tarif ?? [],
        BARANGDOKUMEN: input.barang_dokumen ?? [],
        BARANGENTITAS: input.barang_entitas ?? [],
        BARANGKHUSUS: input.barang_khusus ?? [],
        BARANGVD: input.barang_vd ?? [],
        BAHANBAKU: input.bahan_baku ?? [],
        BAHANBAKUTARIF: input.bahan_tarif ?? [],
        BAHANABAKUDOKUMEN: input.bahan_baku_dokumen ?? [],
        PUNGUTAN: input.punutan ?? [],
        JAMINAN: input.jaminan ?? [],
        BANKDEVISA: input.bank_devisa ?? [],
        VERSI: input.versi ?? [],
        RESPON: input.respon ?? [],

    };

};

export { TransformData }