"use server";
import { prisma } from '@/lib/prisma/init';
import type { Header } from "@prisma/client";
import { auth } from "@/auth";

export async function CreateHeader(header: Header | Header[]) {
    const session = await auth();
    const headersArray = Array.isArray(header) ? header : [header];
    const result = headersArray.map(async (item: any) => {
        try {
            await prisma.header.create({
                data: {
                    nomor_aju: item['NOMOR AJU']?.toString() || "",
                    kode_dokumen: item['KODE DOKUMEN']?.toString() || "",
                    kode_kantor: item['KODE KANTOR']?.toString() || "",
                    kode_kantor_bongkar: item['KODE KANTOR BONGKAR']?.toString() || "",
                    kode_kantor_periksa: item['KODE KANTOR PERIKSA']?.toString() || "",
                    kode_kantor_tujuan: item['KODE KANTOR TUJUAN']?.toString() || "",
                    kode_kantor_ekspor: item['KODE KANTOR EKSPOR']?.toString() || "",
                    kode_jenis_impor: item['KODE JENIS IMPOR']?.toString() || "",
                    kode_jenis_ekspor: item['KODE KANTOR EKSPOR']?.toString() || "",
                    kode_jenis_tpb: item['KODE JENIS TPB']?.toString() || "",
                    kode_jenis_plb: item['KODE JENIS PLB']?.toString() || "",
                    kode_jenis_prosedur: item['KODE JENIS PROSEDUR']?.toString() || "",
                    kode_tujuan_pemasukan: item['KODE TUJUAN PEMASUKAN']?.toString() || "",
                    kode_tujuan_pengiriman: item['KODE TUJUAN PENGIRIMAN']?.toString() || "",
                    kode_tujuan_tpb: item['KODE TUJUAN TPB']?.toString() || "",
                    kode_cara_dagang: item['KODE CARA DAGANG']?.toString() || "",
                    kode_cara_bayar: item['KODE CARA BAYAR']?.toString() || "",
                    kode_cara_bayar_lainnya: item['KODE CARA BAYAR LAINNYA']?.toString() || "",
                    kode_gudang_asal: item['KODE GUDANG ASAL']?.toString() || "",
                    kode_gudang_tujuan: item['KODE GUDANG TUJUAN']?.toString() || "",
                    kode_jenis_kirim: item['KODE JENIS KIRIM']?.toString() || "",
                    kode_jenis_pengiriman: item['KODE JENIS PENGIRIMAN']?.toString() || "",
                    kode_kategori_ekspor: item['KODE KATEGORI EKSPOR']?.toString() || "",
                    kode_kategori_masuk_ftz: item['KODE KATEGORI MASUK FTZ']?.toString() || "",
                    kode_kategori_keluar_ftz: item['KODE KATEGORI KELUAR FTZ']?.toString() || "",
                    kode_kategori_barang_ftz: item['KODE KATEGORI BARANG FTZ']?.toString() || "",
                    kode_lokasi: item['KODE LOKASI']?.toString() || "",
                    kode_lokasi_bayar: item['KODE LOKASI BAYAR']?.toString() || "",
                    lokasi_asal: item['LOKASI ASAL']?.toString() || "",
                    lokasi_tujuan: item['LOKASI TUJUAN']?.toString() || "",
                    kode_daerah_asal: item['KODE DAERAH ASAL']?.toString() || "",
                    kode_negara_tujuan: item['KODE NEGARA TUJUAN']?.toString() || "",
                    kode_tutup_pu: item['KODE TUTUP PU']?.toString() || "",
                    nomor_bc11: item['NOMOR BC11']?.toString() || "",
                    tanggal_bc11: item['TANGGAL BC11']?.toString() || "",
                    nomor_pos: item['NOMOR POS']?.toString() || "",
                    nomor_sub_pos: item['NOMOR SUB POS']?.toString() || "",
                    kode_pelabuhan_bongkar: item['KODE PELABUHAN BONGKAR']?.toString() || "",
                    kode_pelabuhan_muat: item['KODE PELABUHAN MUAT']?.toString() || "",
                    kode_pelabuhan_muat_akhir: item['KODE PELABUHAN MUAT AKHIR']?.toString() || "",
                    kode_pelabuhan_transit: item['KODE PELABUHAN TRANSIT']?.toString() || "",
                    kode_pelabuhan_tujuan: item['KODE PELABUHAN TUJUAN']?.toString() || "",
                    kode_pelabuhan_ekspor: item['KODE PELABUHAN EKSPOR']?.toString() || "",
                    kode_tps: item['KODE TPS']?.toString() || "",
                    tanggal_berangkat: item['TANGGAL BERANGKAT']?.toString() || "",
                    tanggal_ekspor: item['TANGGAL EKSPOR']?.toString() || "",
                    tanggal_masuk: item['TANGGAL MASUK']?.toString() || "",
                    tanggal_muat: item['TANGGAL MUAT']?.toString() || "",
                    tanggal_tiba: item['TANGGAL TIBA']?.toString() || "",
                    tanggal_periksa: item['TANGGAL PERIKSA']?.toString() || "",
                    tempat_stuffing: item['TEMPAT STUFFING']?.toString() || "",
                    tanggal_stuffing: item['TANGGAL STUFFING']?.toString() || "",
                    kode_tanda_pengaman: item['KODE TANDA PENGAMAN']?.toString() || "",
                    jumlah_tanda_pengaman: item['JUMLAH TANDA PENGAMAN']?.toString() || "",
                    flag_curah: item['FLAG CURAH']?.toString() || "",
                    flag_sda: item['FLAG SDA']?.toString() || "",
                    flag_vd: item['FLAG VD']?.toString() || "",
                    flag_ap_bk: item['FLAG AP BK']?.toString() || "",
                    flag_migas: item['FLAG MIGAS']?.toString() || "",
                    kode_asuransi: item['KODE ASURANSI']?.toString() || "",
                    asuransi: parseFloat(item['ASURANSI'] !== null && item['ASURANSI'] !== undefined ? item['ASURANSI']?.toString() : "0"),
                    nilai_barang: parseFloat(item['NILAI BARANG'] !== null && item['NILAI BARANG'] !== undefined ? item['NILAI BARANG']?.toString() : "0"),
                    nilai_incoterm: parseFloat(item['NILAI INCOTERM'] !== null && item['NILAI INCOTERM'] !== undefined ? item['NILAI INCOTERM']?.toString() : "0"),
                    nilai_maklon: parseFloat(item['NILAI MAKLON'] !== null && item['NILAI MAKLON'] !== undefined ? item['NILAI MAKLON']?.toString() : "0"),
                    freight: parseFloat(item['FREIGHT'] !== null && item['FREIGHT'] !== undefined ? item['FREIGHT']?.toString() : "0"),
                    fob: parseFloat(item['FOB'] !== null && item['FOB'] !== undefined ? item['FOB']?.toString() : "0"),
                    biaya_tambahan: parseFloat(item['BIAYA TAMBAHAN'] !== null && item['BIAYA TAMBAHAN'] !== undefined ? item['BIAYA TAMBAHAN']?.toString() : "0"),
                    biaya_pengurang: parseFloat(item['BIAYA PENGURANG'] !== null && item['BIAYA PENGURANG'] !== undefined ? item['BIAYA PENGURANG']?.toString() : "0"),
                    vd: parseFloat(item['VD'] !== null && item['VD'] !== undefined ? item['VD']?.toString() : "0"),
                    cif: parseFloat(item['CIF'] !== null && item['CIF'] !== undefined ? item['CIF']?.toString() : "0"),
                    harga_penyerahan: parseFloat(item['HARGA_PENYERAHAN'] !== null && item['HARGA_PENYERAHAN'] !== undefined ? item['HARGA_PENYERAHAN']?.toString() : "0"),
                    ndpbm: parseFloat(item['NDPBM'] !== null && item['NDPBM'] !== undefined ? item['NDPBM']?.toString() : "0"),
                    total_dana_sawit: parseFloat(item['TOTAL DANA SAWIT'] !== null && item['TOTAL DANA SAWIT'] !== undefined ? item['TOTAL DANA SAWIT']?.toString() : "0"),
                    dasar_pengenaan_pajak: parseFloat(item['DASAR PENGENAAN PAJAK'] !== null && item['DASAR PENGENAAN PAJAK'] !== undefined ? item['DASAR PENGENAAN PAJAK']?.toString() : "0"),
                    nilai_jasa: parseFloat(item['NILAI JASA'] !== null && item['NILAI JASA'] !== undefined ? item['NILAI JASA']?.toString() : "0"),
                    uang_muka: Number(item['UANG MUKA'] || 0),
                    bruto: Number(item['BRUTO'] || 0),
                    netto: Number(item['NETTO'] || 0),
                    volume: Number(item['VOLUME'] || 0),
                    kota_pernyataan: item['KOTA PERNYATAAN']?.toString() || "",
                    tanggal_pernyataan: item['TANGGAL PERNYATAAN']?.toString() || "",
                    nama_pernyataan: item['NAMA PERNYATAAN']?.toString() || "",
                    jabatan_pernyataan: item['JABATAN PERNYATAAN']?.toString() || "",
                    kode_valuta: item['KODE VALUTA']?.toString() || "",
                    kode_incoterm: item['KODE INCOTERM']?.toString() || "",
                    kode_jasa_kena_pajak: item['KODE JASA KENA PAJAK']?.toString() || "",
                    nomor_bukti_bayar: item['NOMOR BUKTI BAYAR']?.toString() || "",
                    tanggal_bukti_bayar: item['TANGGAL BUKTI BAYAR']?.toString() || "",
                    kode_jenis_nilai: item['KODE JENIS NILAI']?.toString() || "",
                    nomor_daftar: item['NOMOR DAFTAR']?.toString() || "",
                    tanggal_daftar: item['TANGGAL DAFTAR']?.toString() + "T00:00:00.000000Z" || "1999-01-01T00:00:00.000000Z",
                    kode_kantor_muat: item['KODE KANTOR MUAT']?.toString() || "",
                    kode_asal_barang_ftz: item['KODE ASAL BARANG FTZ']?.toString() || "",
                    kode_tujuan_pengeluaran: item['KODE TUJUAN PENGELUARAN']?.toString() || "",
                    ppn_pajak: item['PPN PAJAK']?.toString() || "",
                    ppnbm_pajak: item['PPNBM PAJAK']?.toString() || "",
                    tarif_ppn_pajak: item['TARIF PPN PAJAK']?.toString() || "",
                    tarif_ppnbm_pajak: item['TARIF PPNBM PAJAK']?.toString() || "",
                    barang_tidak_berwujud: item['BARANG TIDAK BERWUJUD']?.toString() || "",
                    kode_jenis_pengeluaran: item['KODE JENIS PENGELUARAN']?.toString() || "",
                    barang_kiriman: item['BARANG KIRIMAN']?.toString() || "",
                    kode_jenis_pengangkutan: item['KODE JENIS PENGANGKUTAN']?.toString() || "",
                    create_by: session?.user?.email || "",
                    created_at: item.created_at,
                    updated_at: item.updated_at,
                }
            })
            return Response.json({ message: "Success", status: true }, { status: 200 })
        } catch (error) {
            return error
        }
    });
    return Promise.all(result);
}