name: Deploy Next.js to Windows Server with Docker Compose

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "URL=${{ secrets.URL }}" >> .env

      - name: Build & Recreate container (rolling)
        run: docker compose up -d --build --remove-orphans
